#!/usr/bin/env bash
# shellcheck disable=SC2016
# installing and configuration of Haproxy 
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 46964-web-01	54.157.174.213:80 check
    server 46964-web-02 35.153.194.184:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
